# Descargar imagen
FROM debian:stable

# Instalar paquetes necesarios para compilacion
RUN apt-get update
RUN apt-get install -y --assume-yes \
  apt-utils \
  dialog
RUN apt-get install -y build-essential \
  cmake libreadline-dev sudo \
  valgrind vim bash git flex bison

# Crear usuario docker
RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER docker

# Clonar rama de dev
WORKDIR /home/docker/
RUN git clone https://github.com/primitivorm/latino --branch dev
WORKDIR /home/docker/latino
RUN git checkout dev

# Crear archivos de flex y bison para el analizar lexico / sintactico
WORKDIR /home/docker/latino/tools/parser
RUN flex latlex.l
RUN bison -y latparse.y
RUN mv *.c ../../src
RUN mv *.h ../../include

WORKDIR /home/docker/latino

# Compilar latino en modo Debug
RUN cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" .
RUN make
RUN sudo make install

RUN git config --global user.email "cibercafe_montero@hotmail.com"
RUN git config --global user.name "primitivorm"

# Ejecutar latino
# WORKDIR /home/docker/latino/src
# CMD ["latino", "../ejemplos/02-hola.lat"]